CREATE OR REPLACE PACKAGE OWN_FUNCESP.PKG_EXT_PREVIDENCIARIO IS

 -- VARIAVEIS
  G_HOST_NAME    VARCHAR2(64);

  G_TPO_DADO      ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.TPO_DADO%TYPE;
  G_COD_EMPRS     ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.COD_EMPRS%TYPE;
  G_DTA_FIM_EXTR  ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DTA_FIM_EXTR%TYPE;
  G_DTA_EMISS     ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DTA_EMISS%TYPE;
  G_DCR_PLANO     ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DCR_PLANO%TYPE;
  G_CONT_TEMP     NUMBER := 0;
  G_COUNT_LOG     NUMBER := 0;
  G_CKECK         CHAR(1):= '';
  G_OBS           VARCHAR2(100) := 'EXTRATO PREVIDENCIARIO: ';
  G_MODULE        VARCHAR2(255) := '';
  G_OS_USER       VARCHAR2(255) := '';
  G_TERMINAL      VARCHAR2(255) := '';
  G_CURRENT_USER  VARCHAR2(255) := '';
  G_IP_ADDRESS    VARCHAR2(255) := '';


  G_ARQ          UTL_FILE.FILE_TYPE;
  G_DIR          VARCHAR2(50)   := '/lwork/work';
  G_READ         CHAR(1)        := 'R';
  G_WRITING      CHAR(1)        := 'W';
  G_SIZE         NUMBER         := 32767;


    FUNCTION FUN_CARGA_STAGE ( P_CALCULO NUMBER) RETURN VARCHAR2;

    PROCEDURE PRC_CARGA_ARQUIVO ( P_NAME_ARQ VARCHAR2 DEFAULT NULL);

    PROCEDURE PRC_GERA_ARQ_CSV ( P_NAME_ARQ VARCHAR2 DEFAULT NULL);

    FUNCTION FN_TRATA_ARQUIVO RETURN BOOLEAN;

    PROCEDURE PROC_EXT_PREV_TIETE(  P_COD_EMPRESA   ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.COD_EMPRS%TYPE
                                   ,P_DCR_PLANO     ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DCR_PLANO%TYPE
                                   ,P_DTA_MOV       ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DTA_FIM_EXTR%TYPE DEFAULT NULL);


    PROCEDURE PROC_EXT_PREV_ELETROPAULO(  PCOD_EMPRESA ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.COD_EMPRS%TYPE
                                         ,PDCR_PLANO   ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DCR_PLANO%TYPE
                                         ,PDTA_MOV     ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DTA_FIM_EXTR%TYPE DEFAULT NULL);


    PROCEDURE PRE_INICIA_PROCESSAMENTO(  P_PRC_PROCESSO NUMBER DEFAULT NULL
                                        ,P_PRC_DATA     ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DTA_FIM_EXTR%TYPE DEFAULT NULL
                                        ,P_NAME_ARQ     VARCHAR2 DEFAULT NULL);


END PKG_EXT_PREVIDENCIARIO;
/
